spring.application.name=cruddemo
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=aezakmi

spring.jpa.hibernate.ddl-auto=create-drop